spring.application.name=saitenweise-backend
# Change the server port to 8081
server.port=8081
# Enable pretty JSON output
spring.jackson.serialization.indent-output=true
# only update DB schema (keep existing data)
spring.jpa.hibernate.ddl-auto=update

# Database configuration
spring.datasource.url=jdbc:h2:file:./target/saitenweise-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

## Use this config for MariaDB
#spring.datasource.url=jdbc:mariadb://host:port/dbname
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.datasource.username=user
#spring.datasource.password=password or better use SPRING_DATASOURCE_PASSWORD env variable

# auth0 configuration
okta.oauth2.issuer=https://dev-m7r3to5keud2gw65.us.auth0.com/
okta.oauth2.audience=https://saitenweise.api

# increase logging for security debugging
#logging.level.org.springframework.security=DEBUG
#logging.level.com.okta.spring=DEBUG
